#!/bin/bash


# This script lists all the layers in $image_name docker image,
# ordered by their size
# The default image name is: develeap_timer.
#
# You can pass parameter for diffrent image name.

# Autor: Lior Ben Ami
# Date:  Jan 2021


image_name="develeap_timer" # default image_name

# if input parameter, use it as image_id
if [[ $1 ]]; then
    image_name=$1
fi

image_id=`/usr/bin/docker images $image_name -q`

printf "Getting history for image name: $image_name sorted by layer size \n\n"

/usr/bin/docker history -H=false --format table ${image_id} | \
awk 'NR==1 {print}' #print header

/usr/bin/docker history -H=false --format table ${image_id} | \
awk 'NR!=1 {print}' |  # print all without header 
awk '{ if ($NF != 0) {print}}' |   #dont print rows with size=0
awk '{print $NF,$0}' |  #copy size column to first column
sort -n |  #sort by first column (size)
cut -f2- -d' ' #remove the first column

